### ISSUE TITLE
Multiple 'server' directives in unbound.conf breaks the script.

### ISSUE THREAD

**Issue by kissglay** [MartineauUK/Unbound-Asuswrt-Merlin#6]
If you have multiple 'server:' directives in 'unbound.conf', it pretty much ruins the UI.
The culprits are following code:
`local POS="$(grep -Enw "[[:space:]]*server:" ${CONFIG_DIR}unbound.conf | cut -d':' -f1)"        # v2.14
local LINE="$(tail -n +$POS ${CONFIG_DIR}unbound.conf | grep -E "^[[:blank:]]*[^#]" | grep -E "$KEYWORD")"  # v2.14`
which assign all line number where 'server:' is located to var 'POS', making 3rd parameter feeded to tail a line number.
Because these are called almost every refresh of the Menu to fetch the function activated, so the whole menu is messed up.

**Comment by MartineauUK** [comment]
> If you have multiple 'server:' directives in 'unbound.conf', it pretty much ruins the UI.
> The culprits are following code:
> `local POS="$(grep -Enw "[[:space:]]*server:" ${CONFIG_DIR}unbound.conf | cut -d':' -f1)" # v2.14 local LINE="$(tail -n +$POS ${CONFIG_DIR}unbound.conf | grep -E "^[[:blank:]]*[^#]" | grep -E "$KEYWORD")" # v2.14`
> which assign all line number where 'server:' is located to var 'POS', making 3rd parameter feeded to tail a line number.
> Because these are called almost every refresh of the Menu to fetch the function activated, so the whole menu is messed up.

Not sure why there would be multiple **'server:'**  directives in **'unbound.conf'**?...certainly '**unbound_manager**' _didn't_ put them there. ;-)

The original **$POS** code was designed to avoid '**server:**' _literals_ from being detected in the change header, so that the search for the required directive starts from the real '**server:**' definition.

NOTE: Not being the SME, I wasn't aware that multiple '**server:**' directives are allowed, but I suspect for a single 'server:' directive is the norm?

Do you have a use case for multiple '**server:**' directives?

So, if I assume your pull request would require matching on the **first** '**server:**' directive rather than the **last**?

**Comment by kissglay** [comment]
In my case, I use multiple 'domain-insecure:" under sever section to bypass several sites with broken DNSSEC, and I append them to the end of the file.
I think I can use 'include' to workaround this.

**Comment by MartineauUK** [comment]
Yes, **'include:**' would certainly be an option but then '**unbound_manager**' would not be able to reliably search '**unbound.conf**' for the complete configuration :-(

However, thank you for bringing this to my attention.

I will add the follow patch (x2) in '**unbound_manager**' **v3.00** 

`local POS="$(grep -Enw "[[:space:]]*server:" ${CONFIG_DIR}unbound.conf | head -n 1 | cut -d':' -f1)"   #  Hotfix v2.18.00 v2.05`

but then I have to cater for the following scenario

`server:
   num-threads 11
server:
   num-threads 1`

i.e. start search from the _first_ '**server:**' directive, but extract the _last_ **'num-threads:**' directive >sigh>
